### ISSUE TITLE
x_center and y_center undefined

### ISSUE THREAD

**Issue by demigh0d** [LucasBerbesson/Laser-cat#1]
// finding center of square for starting point
int random_delay;
float x_position = min_x + (max_x - min_x)/2;
float y_position = min_y + (max_y - min_y)/2; 
float x_old_position = x_position;
float y_old_position = y_position;
float x_new_position;
float y_new_position;
float x_speed;
float y_speed;
int movement_time;

fixed by adding declarations after x_position and y_position

// finding center of square for starting point
int random_delay;
float x_position = min_x + (max_x - min_x)/2;
float y_position = min_y + (max_y - min_y)/2; 
**float x_center = x_position;
float y_center = y_position;**
float x_old_position = x_position;
float y_old_position = y_position;
float x_new_position;
float y_new_position;
float x_speed;
float y_speed;
int movement_time;

**Comment by LucasBerbesson** [comment]
Thanks, I fixed that ! x_center and y_center were some old variables that are no longer useful.
